### PR TITLE
Update README.md to add systemd service

### PR DESCRIPTION
**Pull request by irnutsmurt**
Add steps for users to easily create a systemd service so SantaBot will persist after restart or powered down

### CODE REVIEW

**Review by avchikar97 — DISMISSED** [review]
Looks good to me!

**Review by avchikar97 — CHANGES_REQUESTED** [review]
This PR seems like it's just #54 without the santabot.service. Should I close this in favor of that one?

**Comment by irnutsmurt** [comment]
> This PR seems like it's just #54 without the santabot.service. Should I close this in favor of that one?

Thats correct, sorry I'm a github noob

**Comment by avchikar97** [comment]
Lol all good. This is my first time with the review system on GitHub too.

I'll go ahead and close this then since #54 has been approved and merged.

**Pull request closed without merging**
